module CitiesFactory
  City.create(city_name: 'Tokyo', state: '', country: 'Japan')
  City.create(city_name: 'Jakarta', state: '', country: 'Indonesia')
  City.create(city_name: 'Delhi', state: '', country: 'India')
  City.create(city_name: 'Manila', state: '', country: 'Philippines')
  City.create(city_name: 'New York City', state: 'NY', country: 'United States')
  City.create(city_name: 'South Korea', state: '', country: 'South Korea')
  City.create(city_name: 'Shanghai', state: '', country: 'China')
  City.create(city_name: 'Karachi', state: '', country: 'Pakistan')
  City.create(city_name: 'Beijing', state: '', country: 'China')
  City.create(city_name: 'Guangzhou', state: '', country: 'China')
  City.create(city_name: 'Sao Paulo', state: '', country: 'Brazil')
  City.create(city_name: 'Mexico City', state: '', country: 'Mexico')
  City.create(city_name: 'Mumbai', state: '', country: 'India')
  City.create(city_name: 'Kyoto', state: '', country: 'Japan')
  City.create(city_name: 'Moscow', state: '', country: 'Russia')
  City.create(city_name: 'Dhaka', state: '', country: 'Bangladesh')
  City.create(city_name: 'Cairo', state: '', country: 'Egypt')
  City.create(city_name: 'Los Angeles', state: 'CA', country: 'United States')
  City.create(city_name: 'Bangkok', state: '', country: 'Thailand')
  City.create(city_name: 'Kolkata', state: '', country: 'India')
  City.create(city_name: 'Buenos Aires', state: '', country: 'Argentina')
  City.create(city_name: 'Tehran', state: '', country: 'Iran')
  City.create(city_name: 'Istanbul', state: '', country: 'Turkey')
  City.create(city_name: 'Lagos', state: '', country: 'Nigeria')
  City.create(city_name: 'Shenzhen', state: '', country: 'China')
  City.create(city_name: 'Rio de Janeiro', state: '', country: 'Brazil')
  City.create(city_name: 'Kinshasa', state: '', country: 'Democratic Republic of the Congo')
  City.create(city_name: 'Tianjin', state: '', country: 'China')
  City.create(city_name: 'Paris', state: '', country: 'France')
  City.create(city_name: 'Lima', state: '', country: 'Peru')
  City.create(city_name: 'Chengdu', state: '', country: 'China')
  City.create(city_name: 'London', state: '', country: 'United Kingdom')
  City.create(city_name: 'Nagoya', state: '', country: 'Japan')
  City.create(city_name: 'Lahore', state: '', country: 'Pakistan')
  City.create(city_name: 'Bengaluru', state: '', country: 'India')
  City.create(city_name: 'Chicago', state: 'Illinois', country: 'United States')
  City.create(city_name: 'Surabaya', state: '', country: 'Indonesia')
  City.create(city_name: 'Bogota', state: '', country: 'Colombia')
  City.create(city_name: 'Ho Chi Minh City', state: '', country: 'Vietnam')
  City.create(city_name: 'Hyderabad', state: '', country: 'India')
  City.create(city_name: 'Chennai', state: '', country: 'India')
  City.create(city_name: 'Dongguan', state: '', country: 'China')
  City.create(city_name: 'Johannesburg', state: '', country: 'South Africa')
  City.create(city_name: 'Wuhan', state: '', country: 'China')
  City.create(city_name: 'Taipei', state: '', country: 'Taiwan')
  City.create(city_name: 'Hangzhou', state: '', country: 'China')
  City.create(city_name: 'Hong Kong', state: '', country: 'China')
  City.create(city_name: 'Chongqing', state: '', country: 'China')
  City.create(city_name: 'Ahmedabad', state: '', country: 'India')
  City.create(city_name: 'Kuala Lumpur', state: '', country: 'Malaysia')
  City.create(city_name: 'Quanzhou', state: '', country: 'China')
  City.create(city_name: 'Dusseldorf', state: '', country: 'Germany')
  City.create(city_name: 'Baghdad', state: '', country: 'Iraq')
  City.create(city_name: 'Torronto', state: '', country: 'Canada')
  City.create(city_name: 'Santiago', state: '', country: 'Chile')
  City.create(city_name: 'Dallas', state: 'TX', country: 'United States')
  City.create(city_name: 'Madrid', state: '', country: 'Spain')
  City.create(city_name: 'Nanjing', state: '', country: 'China')
  City.create(city_name: 'Shenyang', state: '', country: 'China')
  City.create(city_name: 'Xian–Xianyang', state: '', country: 'China')
  City.create(city_name: 'San Francisco', state: 'CA', country: 'United States')
  City.create(city_name: 'Luanda', state: '', country: 'Angola')
  City.create(city_name: 'Qingdao', state: '', country: 'China')
  City.create(city_name: 'Houston', state: 'TX', country: 'United States')
  City.create(city_name: 'Miami', state: 'FL', country: 'United States')
  City.create(city_name: 'Bandung', state: '', country: 'Indonesia')
  City.create(city_name: 'Riyadh', state: '', country: 'Saudi Arabia')
  City.create(city_name: 'Pune', state: '', country: 'India')
  City.create(city_name: 'Singapore', state: '', country: 'Singapore')
  City.create(city_name: 'Philadelphia', state: 'PA', country: 'United States')
  City.create(city_name: 'Surat', state: '', country: 'India')
  City.create(city_name: 'Milan', state: '', country: 'Italy')
  City.create(city_name: 'Suzhou', state: '', country: 'China')
  City.create(city_name: 'Saint Petersburg', state: '', country: 'Russia')
  City.create(city_name: 'Khartoum', state: '', country: 'Sudan')
  City.create(city_name: 'Atlanta', state: 'GA', country: 'United States')
  City.create(city_name: 'Zhengzhou', state: '', country: 'China')
  City.create(city_name: 'Washington', state: 'DC', country: 'United States')
  City.create(city_name: 'Harbin', state: '', country: 'China')
  City.create(city_name: 'Abidjan', state: '', country: 'Ivory Coast')
  City.create(city_name: 'Yangon', state: '', country: 'Myanmar')
  City.create(city_name: 'Nairobi', state: '', country: 'Kenya')
  City.create(city_name: 'Barcelona', state: '', country: 'Spain')
  City.create(city_name: 'Alexandria', state: '', country: 'Egypt')
  City.create(city_name: 'Kabul', state: '', country: 'Afghanistan')
  City.create(city_name: 'Guadalajara', state: '', country: 'Mexico')
  City.create(city_name: 'Ankara', state: '', country: 'Turkey')
  City.create(city_name: 'Belo Horizonte', state: '', country: 'Brazil')
  City.create(city_name: 'Boston', state: 'MA', country: 'United States')
  City.create(city_name: 'Xiamen', state: '', country: 'China')
  City.create(city_name: 'Kuwait City', state: '', country: 'Kuwait')
  City.create(city_name: 'Dar es Salaam', state: '', country: 'Tanzania')
  City.create(city_name: 'Phoenix', state: 'AZ', country: 'United States')
  City.create(city_name: 'Dalian', state: '', country: 'China')
  City.create(city_name: 'Accra', state: '', country: 'Ghana')
  City.create(city_name: 'Montreal', state: '', country: 'Canada')
  City.create(city_name: 'Monterrey', state: '', country: 'Mexico')
  City.create(city_name: 'Berlin', state: '', country: 'Germany')
  City.create(city_name: 'Sydney', state: '', country: 'Australia')
  City.create(city_name: 'Fuzhou', state: '', country: 'China')
  City.create(city_name: 'Medan', state: '', country: 'Indonesia')
  City.create(city_name: 'Dubai', state: '', country: 'United Arab Emirates')
  City.create(city_name: 'Melbourne', state: '', country: 'Australia')
  City.create(city_name: 'Rome', state: '', country: 'Italy')
  City.create(city_name: 'Cape Town', state: '', country: 'South Africa')
  City.create(city_name: 'Busan', state: '', country: 'South Korea')
  City.create(city_name: 'Jinan', state: '', country: 'China')
  City.create(city_name: 'Ningbo', state: '', country: 'China')
  City.create(city_name: 'Hanoi', state: '', country: 'Vietnam')
  City.create(city_name: 'Naples', state: '', country: 'Italy')
  City.create(city_name: 'Taiyuan', state: '', country: 'China')
  City.create(city_name: 'Jeddah', state: '', country: 'Saudi Arabia')
  City.create(city_name: 'Detroit', state: 'MI', country: 'United States')
  City.create(city_name: 'Hefei', state: '', country: 'China')
  City.create(city_name: 'Changsha', state: '', country: 'China')
  City.create(city_name: 'Kunming', state: '', country: 'China')
  City.create(city_name: 'Wuxi', state: '', country: 'China')
  City.create(city_name: 'Medellin', state: '', country: 'Colombia')
  City.create(city_name: 'Faisalabad', state: '', country: 'Pakistan')
  City.create(city_name: 'Aleppo', state: '', country: 'Syria')
  City.create(city_name: 'Kano', state: '', country: 'Nigeria')
  City.create(city_name: 'Dakar', state: '', country: 'Senegal')
  City.create(city_name: 'Athens', state: '', country: 'Greece')
  City.create(city_name: 'Changzhou', state: '', country: 'China')
  City.create(city_name: 'Durban', state: '', country: 'South Africa')
  City.create(city_name: 'Porto Alegre', state: '', country: 'Brazil')
  City.create(city_name: 'Jaipur', state: '', country: 'India')
  City.create(city_name: 'Fortaleza', state: '', country: 'Brazil')
  City.create(city_name: 'Addis Ababa', state: '', country: 'Ethiopia')
  City.create(city_name: 'Changchun', state: '', country: 'China')
  City.create(city_name: 'Shijiazhuang', state: '', country: 'China')
  City.create(city_name: 'Recife', state: '', country: 'Brazil')
  City.create(city_name: 'Mashhad', state: '', country: 'Iran')
  City.create(city_name: 'Seattle', state: 'WA', country: 'United States')
  City.create(city_name: 'Casablanca', state: '', country: 'Morocco')
  City.create(city_name: 'Salvador', state: '', country: 'Brazil')
  City.create(city_name: 'Urumqi', state: '', country: 'China')
  City.create(city_name: 'Lucknow', state: '', country: 'India')
  City.create(city_name: 'Chittagong', state: '', country: 'Bangladesh')
  City.create(city_name: 'Wenzhou', state: '', country: 'China')
  City.create(city_name: 'Ibadan', state: '', country: 'Nigeria')
  City.create(city_name: 'Izmir', state: '', country: 'Turkey')
  City.create(city_name: 'Curitiba', state: '', country: 'Brazil')
  City.create(city_name: 'San Diego', state: 'CA', country: 'United States')
  City.create(city_name: 'Yaounde', state: '', country: 'Cameroon')
  City.create(city_name: 'Zhangjiagang', state: '', country: 'China')
  City.create(city_name: 'Kanpur', state: '', country: 'India')
  City.create(city_name: 'Zhongshan', state: '', country: 'China')
  City.create(city_name: 'Sanaa', state: '', country: 'Yemen')
  City.create(city_name: 'Tel Aviv', state: '', country: 'Israel')
  City.create(city_name: 'Guiyang', state: '', country: 'China')
  City.create(city_name: 'Douala', state: '', country: 'Cameroon')
  City.create(city_name: 'Taichung', state: '', country: 'Taiwan')
  City.create(city_name: 'Pretoria', state: '', country: 'South Africa')
  City.create(city_name: 'Santo Domingo', state: '', country: 'Dominican Republic')
  City.create(city_name: 'Hyderabad', state: '', country: 'Pakistan')
  City.create(city_name: 'Caracas', state: '', country: 'Venezuela')
  City.create(city_name: 'Pyongyang', state: '', country: 'North Korea')
  City.create(city_name: 'Kalyan', state: '', country: 'India')
  City.create(city_name: 'Asuncion', state: '', country: 'Paraguay')
  City.create(city_name: 'Minneapolis', state: 'MN', country: 'United States')
  City.create(city_name: 'Lanzhou', state: '', country: 'China')
  City.create(city_name: 'Ouagadougou', state: '', country: 'Burkina Faso')
  City.create(city_name: 'Guayaquil', state: '', country: 'Ecuador')
  City.create(city_name: 'Nagpur', state: '', country: 'India')
  City.create(city_name: 'Lisbon', state: '', country: 'Portugal')
  City.create(city_name: 'Baku', state: '', country: 'Azerbaijan')
  City.create(city_name: 'Rotterdam', state: '', country: 'Netherlands')
  City.create(city_name: 'Campinas', state: '', country: 'Brazil')
  City.create(city_name: 'Manchester', state: '', country: 'United Kingdom')
  City.create(city_name: 'Nanchang', state: '', country: 'China')
  City.create(city_name: 'Tampa', state: 'FL', country: 'United States')
  City.create(city_name: 'Maputo', state: '', country: 'Mozambique')
  City.create(city_name: 'Kaohsiung', state: '', country: 'Taiwan')
  City.create(city_name: 'Algiers', state: '', country: 'Algeria')
  City.create(city_name: 'Nanning', state: '', country: 'China')
  City.create(city_name: 'Sapporo', state: '', country: 'Japan')
  City.create(city_name: 'Damascus', state: '', country: 'Syria')
  City.create(city_name: 'Denver', state: 'CO', country: 'United States')
  City.create(city_name: 'Brasília', state: '', country: 'Brazil')
  City.create(city_name: 'Cebu City', state: '', country: 'Philippines')
  City.create(city_name: 'Fukuoka', state: '', country: 'Japan')
  City.create(city_name: 'Birmingham', state: '', country: 'United Kingdom')
  City.create(city_name: 'Islamabad', state: '', country: 'Pakistan')
  City.create(city_name: 'Kumasi', state: '', country: 'Ghana')
  City.create(city_name: 'Bamako', state: '', country: 'Mali')
  City.create(city_name: 'Coimbatore', state: '', country: 'India')
  City.create(city_name: 'Amman', state: '', country: 'Jordan')
  City.create(city_name: 'Linyi', state: '', country: 'China')
  City.create(city_name: 'Port-au-Prince', state: '', country: 'Haiti')
  City.create(city_name: 'Abuja', state: '', country: 'Nigeria')
  City.create(city_name: 'Shantou', state: '', country: 'China')
  City.create(city_name: 'Indore', state: '', country: 'India')
  City.create(city_name: 'Antananarivo', state: '', country: 'Madagascar')
  City.create(city_name: 'Kozhikode', state: '', country: 'India')
  City.create(city_name: 'Isfahan', state: '', country: 'Iran')
  City.create(city_name: 'Chaoyang–Chaonan', state: '', country: 'China')
  City.create(city_name: 'Daegu', state: '', country: 'South Korea')
  City.create(city_name: 'Tangshan', state: '', country: 'China')
  City.create(city_name: 'Kochi', state: '', country: 'India')
  City.create(city_name: 'Cali', state: '', country: 'Colombia')
  City.create(city_name: 'Shaoxing', state: '', country: 'China')
  City.create(city_name: 'Port Harcourt', state: '', country: 'Nigeria')
  City.create(city_name: 'Vancouver', state: '', country: 'Canada')
  City.create(city_name: 'Huaian', state: '', country: 'China')
  City.create(city_name: 'Baltimore', state: 'MD', country: 'United States')
  City.create(city_name: 'Tashkent', state: '', country: 'Uzbekistan')
  City.create(city_name: 'Kiev', state: '', country: 'Ukraine')
  City.create(city_name: 'Thrissur', state: '', country: 'India')
  City.create(city_name: 'Hohhot', state: '', country: 'China')
  City.create(city_name: 'Harare', state: '', country: 'Zimbabwe')
  City.create(city_name: 'Patna', state: '', country: 'India')
  City.create(city_name: 'Beirut', state: '', country: 'Lebanon')
  City.create(city_name: 'Las Vegas', state: 'NV', country: 'United States')
  City.create(city_name: 'Katowice', state: '', country: 'Poland')
  City.create(city_name: 'Lusaka', state: '', country: 'Zambia')
  City.create(city_name: 'St. Louis', state: 'MO', country: 'United States')
  City.create(city_name: 'Colombo', state: '', country: 'Sri Lanka')
  City.create(city_name: 'Baotou', state: '', country: 'China')
  City.create(city_name: 'San Juan', state: '', country: 'Puerto Rico')
  City.create(city_name: 'Havana', state: '', country: 'Cuba')
  City.create(city_name: 'Gujranwala', state: '', country: 'Pakistan')
  City.create(city_name: 'Mogadishu', state: '', country: 'Somalia')
  City.create(city_name: 'Goiania', state: '', country: 'Brazil')
  City.create(city_name: 'Santa Cruz de la Sierra', state: '', country: 'Bolivia')
  City.create(city_name: 'Malappuram', state: '', country: 'India')
  City.create(city_name: 'Cologne–Bonn', state: '', country: 'Germany')
  City.create(city_name: 'Brussels', state: '', country: 'Belgium')
  City.create(city_name: 'Puebla', state: '', country: 'Mexico')
  City.create(city_name: 'Hamburg', state: '', country: 'Germany')
  City.create(city_name: 'Bhopal', state: '', country: 'India')
  City.create(city_name: 'Kannur', state: '', country: 'India')
  City.create(city_name: 'Orlando', state: 'FL', country: 'United States')
  City.create(city_name: 'Maracaibo', state: '', country: 'Venezuela')
  City.create(city_name: 'Handan', state: '', country: 'China')
  City.create(city_name: 'Lubumbashi', state: '', country: 'Democratic Republic of the Congo')
  City.create(city_name: 'Mbuji-Mayi', state: '', country: 'Democratic Republic of the Congo')
  City.create(city_name: 'Brisbane', state: '', country: 'Australia')
  City.create(city_name: 'Tunis', state: '', country: 'Tunisia')
  City.create(city_name: 'Haikou', state: '', country: 'China')
  City.create(city_name: 'Munich', state: '', country: 'Germany')
  City.create(city_name: 'Kitakyushu', state: '', country: 'Japan')
  City.create(city_name: 'Belem', state: '', country: 'Brazil')
  City.create(city_name: 'Portland', state: 'OR', country: 'United States')
  City.create(city_name: 'San Antonio', state: 'TX', country: 'United States')
  City.create(city_name: 'Tijuana', state: '', country: 'Mexico')
  City.create(city_name: 'Vadodara', state: '', country: 'India')
  City.create(city_name: 'Lomé', state: '', country: 'Togo')
  City.create(city_name: 'Luoyang', state: '', country: 'China')
  City.create(city_name: 'Agra', state: '', country: 'India')
  City.create(city_name: 'Conakry', state: '', country: 'Guinea')
  City.create(city_name: 'Kampala', state: '', country: 'Uganda')
  City.create(city_name: 'Thiruvananthapuram', state: '', country: 'India')
  City.create(city_name: 'Frankfurt', state: '', country: 'Germany')
  City.create(city_name: 'Minsk', state: '', country: 'Belarus')
  City.create(city_name: 'Visakhapatnam', state: '', country: 'India')
  City.create(city_name: 'La Paz', state: '', country: 'Bolivia')
  City.create(city_name: 'Multan', state: '', country: 'Pakistan')
  City.create(city_name: 'Manaus', state: '', country: 'Brazil')
  City.create(city_name: 'Sargodha', state: '', country: 'Pakistan')
  City.create(city_name: 'Sacramento', state: 'CA', country: 'United States')
  City.create(city_name: 'Toluca', state: '', country: 'Mexico')
  City.create(city_name: 'Shiraz', state: '', country: 'Iran')
  City.create(city_name: 'Bucharest', state: '', country: 'Romania')
  City.create(city_name: 'Brazzaville', state: '', country: 'Republic of the Congo')
  City.create(city_name: 'Rabat', state: '', country: 'Morocco')
  City.create(city_name: 'Bursa', state: '', country: 'Turkey')
  City.create(city_name: 'Yogyakarta', state: '', country: 'Indonesia')
  City.create(city_name: 'Adana', state: '', country: 'Turkey')
  City.create(city_name: 'Kunshan', state: '', country: 'China')
  City.create(city_name: 'Cleveland', state: 'OH', country: 'United States')
  City.create(city_name: 'Vienna', state: '', country: 'Austria')
  City.create(city_name: 'Huizhou', state: '', country: 'China')
  City.create(city_name: 'Perth', state: '', country: 'Australia')
  City.create(city_name: 'Nashik', state: '', country: 'India')
  City.create(city_name: 'Barranquilla', state: '', country: 'Colombia')
  City.create(city_name: 'Peshawar', state: '', country: 'Pakistan')
  City.create(city_name: 'Pittsburgh', state: 'PA', country: 'United States')
  City.create(city_name: 'Phnom Penh', state: '', country: 'Cambodia')
  City.create(city_name: 'Quito', state: '', country: 'Ecuador')
  City.create(city_name: 'Warsaw', state: '', country: 'Poland')
  City.create(city_name: 'Vijayawada', state: '', country: 'India')
  City.create(city_name: 'Ludhiana', state: '', country: 'India')
  City.create(city_name: 'Budapest', state: '', country: 'Hungary')
  City.create(city_name: 'Datong', state: '', country: 'China')
  City.create(city_name: 'Yiwu—Dongyang', state: '', country: 'China')
  City.create(city_name: 'Montevideo', state: '', country: 'Uruguay')
  City.create(city_name: 'Tabriz', state: '', country: 'Iran')
  City.create(city_name: 'Johor Bahru', state: '', country: 'Malaysia')
  City.create(city_name: 'Cincinnati', state: 'OH', country: 'United States')
  City.create(city_name: 'Mosul', state: '', country: 'Iraq')
  City.create(city_name: 'Santos', state: '', country: 'Brazil')
  City.create(city_name: 'Mecca', state: '', country: 'Saudi Arabia')
  City.create(city_name: 'Zibo', state: '', country: 'China')
  City.create(city_name: 'Homs', state: '', country: 'Syria')
  City.create(city_name: 'Jilin', state: '', country: 'China')
  City.create(city_name: 'Semarang', state: '', country: 'Indonesia')
  City.create(city_name: 'Davao City', state: '', country: 'Philippines')
  City.create(city_name: 'Amsterdam', state: '', country: 'Netherlands')
  City.create(city_name: 'Indianapolis', state: 'IN', country: 'United States')
  City.create(city_name: 'Austin', state: 'TX', country: 'United States')
  City.create(city_name: 'Yinchuan', state: '', country: 'China')
  City.create(city_name: 'Gwangju', state: '', country: 'South Korea')
  City.create(city_name: 'Weifang', state: '', country: 'China')
  City.create(city_name: 'Kansas City', state: 'MO', country: 'United States')
  City.create(city_name: 'Cordoba', state: '', country: 'Argentina')
  City.create(city_name: 'Taizhou', state: '', country: 'China')
  City.create(city_name: 'Novosibirsk', state: '', country: 'Russia')
  City.create(city_name: 'Lyon', state: '', country: 'France')
  City.create(city_name: 'Madurai', state: '', country: 'India')
  City.create(city_name: 'General Santos', state: '', country: 'Philippines')
  City.create(city_name: 'Liuzhou', state: '', country: 'China')
  City.create(city_name: 'Rajkot', state: '', country: 'India')
  City.create(city_name: 'Doha', state: '', country: 'Qatar')
  City.create(city_name: 'Daejeon', state: '', country: 'South Korea')
  City.create(city_name: 'Yangzhou', state: '', country: 'China')
  City.create(city_name: 'Valencia', state: '', country: 'Spain')
  City.create(city_name: 'Zhuhai—Macau', state: '', country: 'China')
  City.create(city_name: 'Meerut', state: '', country: 'India')
  City.create(city_name: 'Varanasi', state: '', country: 'India')
  City.create(city_name: 'Charlotte', state: 'NC', country: 'United States')
  City.create(city_name: 'Turin', state: '', country: 'Italy')
  City.create(city_name: 'Yantai', state: '', country: 'China')
  City.create(city_name: 'Anshan–Liaoyang', state: '', country: 'China')
  City.create(city_name: 'Almaty', state: '', country: 'Kazakhstan')
  City.create(city_name: 'Panama City', state: '', country: 'Panama')
  City.create(city_name: 'Cixi', state: '', country: 'China')
  City.create(city_name: 'Benin City', state: '', country: 'Nigeria')
  City.create(city_name: 'Makassar', state: '', country: 'Indonesia')
  City.create(city_name: 'Stockholm', state: '', country: 'Sweden')
  City.create(city_name: 'Columbus', state: 'OH', country: 'United States')
  City.create(city_name: 'Yekaterinburg', state: '', country: 'Russia')
  City.create(city_name: 'Valencia', state: '', country: 'Venezuela')
  City.create(city_name: 'Porto', state: '', country: 'Portugal')
  City.create(city_name: 'Leon', state: '', country: 'Mexico')
  City.create(city_name: 'Putian', state: '', country: 'China')
  City.create(city_name: 'Virginia Beach', state: 'VA', country: 'United States')
  City.create(city_name: 'Wuhu', state: '', country: 'China')
  City.create(city_name: 'Jamshedpur', state: '', country: 'India')
  City.create(city_name: 'Kharkiv', state: '', country: 'Ukraine')
  City.create(city_name: 'Palembang', state: '', country: 'Indonesia')
  City.create(city_name: 'Zhangzhou', state: '', country: 'China')
  City.create(city_name: 'Srinagar', state: '', country: 'India')
  City.create(city_name: 'Milwaukee', state: 'WI', country: 'United States')
  City.create(city_name: 'Anyang', state: '', country: 'China')
  City.create(city_name: 'Jiangmen', state: '', country: 'China')
  City.create(city_name: 'Marseille', state: '', country: 'France')
  City.create(city_name: 'Gaziantep', state: '', country: 'Turkey')
  City.create(city_name: 'Ciudad Juarez', state: '', country: 'Mexico')
  City.create(city_name: 'Stuttgart', state: '', country: 'Germany')
  City.create(city_name: 'Hiroshima', state: '', country: 'Japan')
  City.create(city_name: 'Auckland', state: '', country: 'New Zealand')
  City.create(city_name: 'Kollam', state: '', country: 'India')
  City.create(city_name: 'Xining', state: '', country: 'China')
  City.create(city_name: 'Changshu', state: '', country: 'China')
  City.create(city_name: 'Manama', state: '', country: 'Bahrain')
  City.create(city_name: 'Jabalpur', state: '', country: 'India')
  City.create(city_name: 'Rosario', state: '', country: 'Argentina')
  City.create(city_name: 'Penang', state: '', country: 'Malaysia')
  City.create(city_name: 'Raipur', state: '', country: 'India')
  City.create(city_name: 'Torreón', state: '', country: 'Mexico')
  City.create(city_name: 'Fushun', state: '', country: 'China')
  City.create(city_name: 'Aurangabad', state: '', country: 'India')
  City.create(city_name: 'Surakarta', state: '', country: 'Indonesia')
  City.create(city_name: 'Asansol', state: '', country: 'India')
  City.create(city_name: 'Ahvaz', state: '', country: 'Iran')
  City.create(city_name: 'Zurich', state: '', country: 'Switzerland')
  City.create(city_name: 'Prague', state: '', country: 'Czech Republic')
  City.create(city_name: 'Xuzhou', state: '', country: 'China')
  City.create(city_name: 'Baoding', state: '', country: 'China')
  City.create(city_name: 'Allahabad', state: '', country: 'India')
  City.create(city_name: 'Guatemala City', state: '', country: 'Guatemala')
  City.create(city_name: 'Sendai', state: '', country: 'Japan')
  City.create(city_name: 'Nizhny Novgorod', state: '', country: 'Russia')
  City.create(city_name: 'Yerevan', state: '', country: 'Armenia')
  City.create(city_name: 'Jodhpur', state: '', country: 'India')
  City.create(city_name: 'Amritsar', state: '', country: 'India')
  City.create(city_name: 'Huambo', state: '', country: 'Angola')
  City.create(city_name: 'NDjamena', state: '', country: 'Chad')
  City.create(city_name: 'Dhanbad', state: '', country: 'India')
  City.create(city_name: 'Wenling', state: '', country: 'China')
  City.create(city_name: 'Queretaro', state: '', country: 'Mexico')
  City.create(city_name: 'Copenhagen', state: '', country: 'Denmark')
  City.create(city_name: 'Ranchi', state: '', country: 'India')
  City.create(city_name: 'Qiqihar', state: '', country: 'China')
  City.create(city_name: 'Cochabamba', state: '', country: 'Bolivia')
  City.create(city_name: 'Ulan Bator', state: '', country: 'Mongolia')
  City.create(city_name: 'Durg-Bhilai', state: '', country: 'India')
  City.create(city_name: 'Medina', state: '', country: 'Saudi Arabia')
  City.create(city_name: 'Chifeng', state: '', country: 'China')
  City.create(city_name: 'Hama', state: '', country: 'Syria')
  City.create(city_name: 'Glasgow', state: '', country: 'United Kingdom')
  City.create(city_name: 'Kazan', state: '', country: 'Russia')
  City.create(city_name: 'Tainan', state: '', country: 'Taiwan')
  City.create(city_name: 'Port Elizabeth', state: '', country: 'South Africa')
  City.create(city_name: 'Weihai', state: '', country: 'China')
  City.create(city_name: 'Helsinki', state: '', country: 'Finland')
  City.create(city_name: 'Gwalior', state: '', country: 'India')
  City.create(city_name: 'Dongying', state: '', country: 'China')
  City.create(city_name: 'Providence', state: '', country: 'United States')
  City.create(city_name: 'Sofia', state: '', country: 'Bulgaria')
  City.create(city_name: 'Fes', state: '', country: 'Morocco')
  City.create(city_name: 'Chelyabinsk', state: '', country: 'Russia')
  City.create(city_name: 'Jiaxing', state: '', country: 'China')
  City.create(city_name: 'Konya', state: '', country: 'Turkey')
  City.create(city_name: 'Calgary', state: '', country: 'Canada')
  City.create(city_name: 'Hamamatsu', state: '', country: 'Japan')
  City.create(city_name: 'Nantong', state: '', country: 'China')
  City.create(city_name: 'Xiangyang', state: '', country: 'China')
  City.create(city_name: 'Kathmandu', state: '', country: 'Nepal')
  City.create(city_name: 'Belgrade', state: '', country: 'Serbia')
  City.create(city_name: 'Vasai-Virar', state: '', country: 'India')
  City.create(city_name: 'Omsk', state: '', country: 'Russia')
  City.create(city_name: 'Tiruppur', state: '', country: 'India')
  City.create(city_name: 'Denpasar', state: '', country: 'Indonesia')
  City.create(city_name: 'Marrakesh', state: '', country: 'Morocco')
  City.create(city_name: 'Vitoria', state: '', country: 'Brazil')
  City.create(city_name: 'Sao Luis', state: '', country: 'Brazil')
  City.create(city_name: 'Samara', state: '', country: 'Russia')
  City.create(city_name: 'San Jose', state: '', country: 'Costa Rica')
  City.create(city_name: 'Dublin', state: '', country: 'Ireland')
  City.create(city_name: 'Mandalay', state: '', country: 'Myanmar')
  City.create(city_name: 'Zhangjiakou', state: '', country: 'China')
  City.create(city_name: 'Jacksonville', state: 'FL', country: 'United States')
  City.create(city_name: 'Kananga', state: '', country: 'Democratic Republic of the Congo')
  City.create(city_name: 'Erbil', state: '', country: 'Iraq')
  City.create(city_name: 'Cirebon', state: '', country: 'Indonesia')
  City.create(city_name: 'Huainan', state: '', country: 'China')
  City.create(city_name: 'Batam', state: '', country: 'Indonesia')
  City.create(city_name: 'Adelaide', state: '', country: 'Australia')
  City.create(city_name: 'Kota', state: '', country: 'India')
  City.create(city_name: 'San Luis Potosi', state: '', country: 'Mexico')
  City.create(city_name: 'Maracay', state: '', country: 'Venezuela')
  City.create(city_name: 'Ruian', state: '', country: 'China')
  City.create(city_name: 'Lianyungang', state: '', country: 'China')
  City.create(city_name: 'Tbilisi', state: '', country: 'Georgia')
  City.create(city_name: 'Chandigarh', state: '', country: 'India')
  City.create(city_name: 'Ufa', state: '', country: 'Russia')
  City.create(city_name: 'Kigali', state: '', country: 'Rwanda')
  City.create(city_name: 'Tegucigalpa', state: '', country: 'Honduras')
  City.create(city_name: 'Rostov-on-Don', state: '', country: 'Russia')
  City.create(city_name: 'Huaibei', state: '', country: 'China')
  City.create(city_name: 'Mombasa', state: '', country: 'Kenya')
  City.create(city_name: 'Malang', state: '', country: 'Indonesia')
  City.create(city_name: 'Merida', state: '', country: 'Mexico')
  City.create(city_name: 'Tripoli', state: '', country: 'Libya')
  City.create(city_name: 'Seville', state: '', country: 'Spain')
  City.create(city_name: 'Memphis', state: 'TN', country: 'United States')
  City.create(city_name: 'Tengzhou', state: '', country: 'China')
  City.create(city_name: 'Qom', state: '', country: 'Iran')
  City.create(city_name: 'San Salvador', state: '', country: 'El Salvador')
  City.create(city_name: 'Pekanbaru', state: '', country: 'Indonesia')
  City.create(city_name: 'Monrovia', state: '', country: 'Liberia')
  City.create(city_name: 'Onitsha', state: '', country: 'Nigeria')
  City.create(city_name: 'Quetta', state: '', country: 'Pakistan')
  City.create(city_name: 'Bareilly', state: '', country: 'India')
  City.create(city_name: 'Bahawalpur', state: '', country: 'Pakistan')
  City.create(city_name: 'Niamey', state: '', country: 'Niger')
  City.create(city_name: 'Jiamusi', state: '', country: 'China')
  City.create(city_name: 'Raleigh', state: 'NC', country: 'United States')
  City.create(city_name: 'Salt Lake City', state: 'UT', country: 'United States')
  City.create(city_name: 'Nashville', state: 'TN', country: 'United States')
  City.create(city_name: 'Hubballi', state: '', country: 'India')
  City.create(city_name: 'Mysore', state: '', country: 'India')
  City.create(city_name: 'Sialkot', state: '', country: 'Pakistan')
  City.create(city_name: 'Antalya', state: '', country: 'Turkey')
  City.create(city_name: 'Krasnoyarsk', state: '', country: 'Russia')
  City.create(city_name: 'Natal', state: '', country: 'Brazil')
  City.create(city_name: 'Joao Pessoa', state: '', country: 'Brazil')
  City.create(city_name: 'Fuzhou', state: '', country: 'China')
  City.create(city_name: 'Puning', state: '', country: 'China')
  City.create(city_name: 'Zhanjiang', state: '', country: 'China')
  City.create(city_name: 'Perm', state: '', country: 'Russia')
  City.create(city_name: 'Qinhuangdao', state: '', country: 'China')
  City.create(city_name: 'Zhucheng', state: '', country: 'China')
  City.create(city_name: 'Yichang', state: '', country: 'China')
  City.create(city_name: 'Guwahati', state: '', country: 'India')
  City.create(city_name: 'Voronezh', state: '', country: 'Russia')
  City.create(city_name: 'Naypyidaw', state: '', country: 'Myanmar')
  City.create(city_name: 'Bucaramanga', state: '', country: 'Colombia')
  City.create(city_name: 'Zaria', state: '', country: 'Nigeria')
  City.create(city_name: 'Louisville', state: 'KY', country: 'United States')
  City.create(city_name: 'Huzhou', state: '', country: 'China')
  City.create(city_name: 'Aligarh', state: '', country: 'India')
  City.create(city_name: 'Aguascalientes', state: '', country: 'Mexico')
  City.create(city_name: 'Kaduna', state: '', country: 'Nigeria')
  City.create(city_name: 'Dammam', state: '', country: 'Saudi Arabia')
  City.create(city_name: 'Lille', state: '', country: 'France')
  City.create(city_name: 'Mexicali', state: '', country: 'Mexico')
  City.create(city_name: 'Richmond', state: 'VA', country: 'United States')
  City.create(city_name: 'Volgograd', state: '', country: 'Russia')
  City.create(city_name: 'Odessa', state: '', country: 'Ukraine')
  City.create(city_name: 'Antwerp', state: '', country: 'Belgium')
  City.create(city_name: 'Xiangtan', state: '', country: 'China')
  City.create(city_name: 'Zhuzhou', state: '', country: 'China')
  City.create(city_name: 'Naha', state: '', country: 'Japan')
  City.create(city_name: 'Moradabad', state: '', country: 'India')
  City.create(city_name: 'Khulna', state: '', country: 'Bangladesh')
  City.create(city_name: 'Kisangani', state: '', country: 'Democratic Republic of the Congo')
  City.create(city_name: 'Basra', state: '', country: 'Iraq')
  City.create(city_name: 'Sulaymaniyah', state: '', country: 'Iraq')
  City.create(city_name: 'Freetown', state: '', country: 'Sierra Leone')
end
