export const Species = [
  { name: 'Krypto God', types: ['Fire', 'Ice'] },
  { name: 'Foxie', types: ['Grass'] },
  { name: 'Yoshibud', types: ['Grass'] },
  { name: 'Dholeaf', types: ['Grass'] },
  { name: 'Bacon', types: ['Fire'] },
  { name: 'Blazehog', types: ['Fire'] },
  { name: 'Infernor', types: ['Fire'] },
  { name: 'Tingadot', types: ['Water'] },
  { name: 'Aquoge', types: ['Water'] },
  { name: 'Seamonte', types: ['Water'] },
  { name: 'Hammy', types: ['Normal'] },
  { name: 'Hamstow', types: ['Normal'] },
  { name: 'Hampop', types: ['Normal'] },
  { name: 'Caternut', types: ['Normal', 'Bug'] },
  { name: 'Papoon', types: ['Normal', 'Bug'] },
  { name: 'Smetterling', types: ['Normal', 'Bug'] },
  { name: 'Caterpeaf', types: ['Grass'] },
  { name: 'Spirilla', types: ['Grass'] },
  { name: 'Fledgy', types: ['Flying', 'Psychic'] },
  { name: 'Hypnobill', types: ['Flying', 'Psychic'] },
  { name: 'Grasschopper', types: ['Bug', 'Fighting'] },
  { name: 'Buzzfly', types: ['Electric', 'Flying', 'Bug'] },
  { name: 'Flaxenbolt', types: ['Electric', 'Flying', 'Bug'] },
  { name: 'Nugget', types: ['Normal'] },
  { name: 'Pumpchick', types: ['Normal'] },
  { name: 'Cheagle', types: ['Normal', 'Flying'] },
  { name: 'Pillama', types: ['Normal'] },
  { name: 'Papillamb', types: ['Normal', 'Flying'] },
  { name: 'Makaha', types: ['Grass', 'Fairy'] },
  { name: 'Waiqiqi', types: ['Grass', 'Fairy'] },
  { name: 'Boohuahua', types: ['Dark'] },
  { name: 'Ghyena', types: ['Dark'] },
  { name: 'Pluffer', types: ['Normal'] },
  { name: '<Species>', types: ['Normal'] },
  { name: 'Lobolf', types: ['Normal'] },
  { name: 'Ocekat', types: ['Water', 'Grass'] },
  { name: 'Otakon', types: ['Water', 'Grass'] },
  { name: 'Darva', types: ['Bug', 'Dark'] },
  { name: 'Assassant', types: ['Bug', 'Dark'] },
  { name: 'Tippytap', types: ['Bug', 'Poison'] },
  { name: 'Taranturat', types: ['Bug', 'Poison'] },
  { name: 'Grumby', types: ['Normal', 'Fighting'] },
  { name: 'Wallaby', types: ['Normal', 'Fighting'] },
  { name: 'Platypoop', types: ['Water', 'Psychic'] },
  { name: 'Duckula', types: ['Water', 'Psychic'] },
  { name: 'Amphibiman', types: ['Water'] },
  { name: '<Species>', types: ['Dark'] },
  { name: 'Boba', types: ['Fairy'] },
  { name: 'Kalinda', types: ['Fairy'] },
  { name: 'Flameling', types: ['Fire', 'Flying'] },
  { name: 'Screech', types: ['Fire', 'Flying'] },
  { name: 'Cinereus', types: ['Fire', 'Flying'] },
  { name: 'Kookoo', types: ['Normal'] },
  { name: 'Koabear', types: ['Normal', 'Dark'] },
  { name: 'Rhinome', types: ['Rock'] },
  { name: 'Rhinomite', types: ['Rock'] },
  { name: 'Merdonk', types: ['Water'] },
  { name: 'Pegafin', types: ['Water'] },
  { name: 'Mustela', types: ['Ghost'] },
  { name: 'Matilda', types: ['Ghost'] },
  { name: 'Nincoon', types: ['Normal', 'Fighting'] },
  { name: 'Rabbite', types: ['Electric'] },
  { name: 'Vulteon', types: ['Electric'] },
  { name: 'Chickapee', types: ['Normal'] },
  { name: 'Sandrunner', types: ['Normal'] },
  { name: '<Species>', types: ['Normal'] },
  { name: '<Species>', types: ['Normal'] },
  { name: '<Species>', types: ['Normal'] },
  { name: 'Rodentice', types: ['Normal', 'Fighting'] },
  { name: 'Ratafu', types: ['Normal', 'Fighting'] },
  { name: 'Scorpine', types: ['Bug'] },
  { name: 'Scorpiton', types: ['Bug', 'Poison'] },
  { name: 'Blobble', types: ['Water'] },
  { name: 'Dolphath', types: ['Water'] },
  { name: '<Species>', types: ['Water'] },
  { name: '<Species>', types: ['Water'] },
  { name: '<Species>', types: ['Water'] },
  { name: '<Species>', types: ['Fire'] },
  { name: '<Species>', types: ['Fire'] },
  { name: '<Species>', types: ['Fire'] },
  { name: 'Zaphog', types: ['Electric'] },
  { name: 'Blutore', types: ['Fighting'] },
  { name: '<Species>', types: ['Dark', 'Fighting'] },
  { name: '<Species>', types: ['Dark', 'Fighting'] },
  { name: 'Yiddle', types: ['Ice', 'Fighting'] },
  { name: 'Yeddi', types: ['Ice', 'Fighting'] },
  { name: 'Harpeon', types: ['Flying'] },
  { name: 'Panzoom', types: ['Ghost'] },
  { name: 'Panloom', types: ['Ghost'] },
  { name: 'Pandoom', types: ['Ghost', 'Dark'] },
  { name: 'Tilla', types: ['Grass', 'Poison'] },
  { name: 'Lacertilla', types: ['Grass', 'Poison'] },
  { name: 'Foge', types: ['Fire'] },
  { name: 'Exploge', types: ['Fire'] },
  { name: 'Uniphin', types: ['Water'] },
  { name: 'Unihorn', types: ['Water'] },
  { name: 'Pritty', types: ['Grass', 'Fairy'] },
  { name: 'Kateline', types: ['Grass', 'Fairy'] },
  { name: 'Skullex', types: ['Ghost', 'Psychic'] },
  { name: 'Goatee', types: ['Fire'] },
  { name: 'Ramfire', types: ['Fire', 'Dark'] },
  { name: '<Species>', types: ['Ground'] },
  { name: 'Scaleton', types: ['Ground'] },
  { name: '<Species>', types: ['Psychic'] },
  { name: 'Abu', types: ['Grass'] },
  { name: 'Geurilla', types: ['Grass'] },
  { name: 'Alphape', types: ['Grass'] },
  { name: 'Stingy', types: ['Water', 'Electric'] },
  { name: 'Thundray', types: ['Water', 'Electric'] },
  { name: 'Gupzee', types: ['Water', 'Electric'] },
  { name: 'Ampacuda', types: ['Water', 'Electric'] },
  { name: 'Staloon', types: ['Steel'] },
  { name: 'Stoldier', types: ['Steel'] },
  { name: 'Supatank', types: ['Steel'] },
  { name: 'Helaloon', types: ['Steel', 'Flying'] },
  { name: 'Metablimp', types: ['Steel', 'Flying'] },
  { name: 'Quadrone', types: ['Steel', 'Flying'] },
  { name: 'Teteo', types: ['Psychic'] },
  { name: 'Tialoc', types: ['Psychic'] },
  { name: '<Species>', types: ['Fire', 'Psychic'] },
  { name: '<Species>', types: ['Fire', 'Psychic'] },
  { name: '<Species>', types: ['Fire', 'Psychic'] },
  { name: '<Species>', types: ['Water'] },
  { name: '<Species>', types: ['Water'] },
  { name: 'Vooboo', types: ['Ghost', 'Psychic'] },
  { name: 'Pinskull', types: ['Ghost', 'Psychic'] },
  { name: 'Skulla', types: ['Ghost', 'Psychic'] },
  { name: 'Skullola', types: ['Ghost', 'Psychic'] },
  { name: '<Species>', types: ['Normal'] },
  { name: '<Species>', types: ['Normal'] },
  { name: '<Species>', types: ['Normal'] },
  { name: 'Metarunt', types: ['Rock', 'Metal'] },
  { name: 'Metastone', types: ['Rock', 'Metal'] },
  { name: 'Metacrush', types: ['Rock', 'Metal'] },
  { name: '<Species>', types: ['Dark', 'Psychic'] },
  { name: '<Species>', types: ['Dark', 'Psychic'] },
  { name: '<Species>', types: ['Dark'] },
  { name: '<Species>', types: ['Dark'] },
  { name: 'Tyranaplode', types: ['Fire', 'Rock'] },
  { name: 'Sleopard', types: ['Ice'] },
  { name: 'Psion', types: ['Fighting', 'Psychic'] },
  { name: 'Volcanor', types: ['Rock', 'Fire'] },
  { name: '<Species>', types: ['Ground', 'Dragon'] },
  { name: 'Siberion', types: ['Ice', 'Dragon'] },
  { name: '<Species>', types: ['Electric', 'Dragon'] },
  { name: '<Species>', types: ['Fire', 'Dragon'] },
  { name: '<Species>', types: ['Grass', 'Dragon'] },
  { name: '<Species>', types: ['Fire', 'Flying'] },
  { name: '<Species>', types: ['Dragon'] },
  { name: 'Luciferium', types: ['Dark'] },
];

export const typeByName = {
  Ground: { color: 'brown' },
  Dragon: { color: 'orange' },
  Rock: { color: 'grey' },
  Fire: { color: 'red' },
  Psychic: { color: 'violet' },
  Grass: { color: 'green' },
  Water: { color: 'blue' },
  Ice: { color: 'teal' },
  Flying: { color: 'orange' },
  Dark: { color: 'purple' },
  Metal: { color: 'grey' },
  Electric: { color: 'yellow' },
  Normal: { color: 'black' },
  Ghost: { color: 'black' },
  Fairy: { color: 'pink' },
  Poison: { color: 'olive' },
  Bug: { color: 'green' },
  Steel: { color: 'grey' },
  Fighting: { color: 'orange' },
};

export const rarityById = {
  1: { color: 'grey', name: 'Common', icon: 'asterisk' },
  2: { color: 'green', name: 'Uncommon', icon: 'asterisk' },
  3: { color: 'teal', name: 'Rare', icon: 'diamond' },
  4: { color: 'blue', name: 'Super Rare', icon: 'diamond' },
  5: { color: 'purple', name: 'Ultra Rare', icon: 'fire' },
  6: { color: 'red', name: 'Mega Rare', icon: 'fire' },
  7: { color: 'orange', name: 'Legendary', icon: 'star' },
};
