json.set! :id, listing.id
json.set! :title, listing.title
json.set! :city, listing.city
json.set! :state, listing.state
json.set! :country, listing.country
json.set! :price, listing.price
json.set! :image_url, listing.image_url
json.set! :lat, listing.lat
json.set! :lng, listing.lng
json.set! :average_rating, listing.average_rating
json.set! :count_reviews, listing.reviews.length
